org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
neo_version=21.1.172
loader_version_range=[4,)
neo_version_range=[21.1.172,)
minecraft_version_range=[1.21.1,1.22)

mod_id=joinmessagemod
mod_name=Join Message Mod
mod_license=MIT
mod_version=1.0.0
mod_group_id=net.kingmihailp.joinmessagemod
mod_authors=KingMihailP
mod_description=Customize or disable join/leave messages with hex color support.
